CREATE TABLE phd(
  "S.No." TEXT PRIMARY KEY UNIQUE,
  "View" TEXT,
  "Application Ref. No." TEXT,
  "Submission Date" TEXT,
  "Payment Status" TEXT,
  "Fee" TEXT,
  "Payment Date" TEXT,
  "Name" TEXT,
  "Gender" TEXT,
  "DOB" TEXT,
  "Nationality" TEXT,
  "Category" TEXT,
  "PwD?" TEXT,
  "Marital Status" TEXT,
  "Email" TEXT,
  "Alt. Email" TEXT,
  "Mobile" TEXT,
  "Father's Name" TEXT,
  "Mother's Name" TEXT,
  "Parent Email Id" TEXT,
  "Aadhaar Number" TEXT,
  "Permanent Address" TEXT,
  "Status" TEXT,
  "Programme" TEXT,
  "Department" TEXT,
  "Preference 1" TEXT,
  "Preference 2" TEXT,
  "Preference 3" TEXT,
  "Phd area of research" TEXT,
  "Institute Assistantship" TEXT,
  "Finance Method" TEXT,
  "Finance Details" TEXT,
  "GATE 2019 Reg ID" TEXT,
  "GATE 2019 Discipline" TEXT,
  "GATE 2019 Score" TEXT,
  "GATE 2019 Rank" TEXT,
  "GATE 2018 Reg ID" TEXT,
  "GATE 2018 Discipline" TEXT,
  "GATE 2018 Score" TEXT,
  "GATE 2018 Rank" TEXT,
  "GATE 2017 Reg ID" TEXT,
  "GATE 2017 Discipline" TEXT,
  "GATE 2017 Score" TEXT,
  "GATE 2017 Rank" TEXT,
  "Other 1 Roll No./ Reg ID" TEXT,
  "Other 1 Score" TEXT,
  "Other 1 Max Score" TEXT,
  "Other 1 Valid Upto" TEXT,
  "Other 1 Test Name" TEXT,
  "Other 1 Test Year" TEXT,
  "Other 1 Discipline" TEXT,
  "Other 1 Rank" TEXT,
  "Percentile" TEXT,
  "Quantitative Aptitude Percentile" TEXT,
  "Data Integration & Logical Reasoning Percentile" TEXT,
  "Verbal & Reading Comprehension Percentile" TEXT,
  "Other 2 Roll No./ Reg ID" TEXT,
  "Other 2 Score" TEXT,
  "Other 2 Max Score" TEXT,
  "Other 2 Valid Upto" TEXT,
  "Other 2 Test Name" TEXT,
  "Other 2 Test Year" TEXT,
  "Other 2 Discipline" TEXT,
  "Other 2 Rank" TEXT,
  "Qualifying Degree" TEXT,
  "Qualifying Discipline" TEXT,
  "University Name" TEXT,
  "University City" TEXT,
  "University Country" TEXT,
  "Institute Name" TEXT,
  "Year of Admission" TEXT,
  "Year of Completion" TEXT,
  "Duration" TEXT,
  "Degree Status" TEXT,
  "Rank" TEXT,
  "Evaluation Pattern" TEXT,
  "Evaluation Method" TEXT,
  "Marks Obtained" TEXT,
  "Maximum Marks" TEXT,
  "Percentage" TEXT,
  "Total Experience" TEXT,
  "Experience 1 Organization" TEXT,
  "Experience 1 Designation" TEXT,
  "Experience 1 From" TEXT,
  "Experience 1 To" TEXT,
  "Experience 1 Roles & Responsibility" TEXT,
  "Experience 1 Total Pay" TEXT,
  "No. of Papers" TEXT,
  "No. of Papers in Conference" TEXT,
  "No. of Papers in Conf Not published" TEXT,
  "No. of Book Chapters" TEXT,
  "Referee 1 Name" TEXT,
  "Referee 1 Organization" TEXT,
  "Referee 1 Email" TEXT,
  "Referee 1 Phone" TEXT,
  "Referee 1 Address" TEXT,
  "Referee 2 Name" TEXT,
  "Referee 2 Organization" TEXT,
  "Referee 2 Email" TEXT,
  "Referee 2 Phone" TEXT,
  "Referee 2 Address" TEXT,
  "PE 1 Degree" TEXT,
  "PE 1 Year" TEXT,
  "PE 1 Board / University" TEXT,
  "PE 1 Subjects" TEXT,
  "PE 1 Score" TEXT,
  "PE 1 Max Score" TEXT,
  "PE 1 Percentage" TEXT,
  "PE 1 Rank" TEXT,
  "PE 2 Degree" TEXT,
  "PE 2 Year" TEXT,
  "PE 2 Board / University" TEXT,
  "PE 2 Subjects" TEXT,
  "PE 2 Score" TEXT,
  "PE 2 Max Score" TEXT,
  "PE 2 Percentage" TEXT,
  "PE 2 Rank" TEXT,
  "PE 3 Degree" TEXT,
  "PE 3 Year" TEXT,
  "PE 3 Board / University" TEXT,
  "PE 3 Subjects" TEXT,
  "PE 3 Score" TEXT,
  "PE 3 Max Score" TEXT,
  "PE 3 Percentage" TEXT,
  "PE 3 Rank" TEXT
, Tutor_name text, Submission text, Comment text, Validation text, alloc_status text);

